---
- name: Install Apache
  sudo: yes
  apt: pkg=apache2 state=latest

- name: Install Apache Modules
  apache2_module: state=present name={{ item }}
  notify: restart apache
  with_items:
    - rewrite
    - vhost_alias
    - headers
    - expires
    - filter

- shell: apache2 -v
  register: apache_version

- name: Configure Apache for user {{ apache_run_user }}
  sudo: yes
  template: src={{ apache_envars_template }} dest={{ apache_path }}/envvars backup=yes
  notify: restart apache

- name: Change default apache2.4 env {{ ws_vhost_env }}
  sudo: yes
  template: src={{ apache24_template }} dest={{ ws_vhost_path }}/{{ ws_vhost_env }}.conf
  notify: restart apache
  when: apache_version.stdout.find('Apache/2.4.') != -1

- name: Change default apache2.2 env {{ ws_vhost_env }} env
  sudo: yes
  template: src={{ apache24_template }} dest={{ ws_vhost_path }}/{{ ws_vhost_env }}.conf
  notify: restart apache
  when: apache_version.stdout.find('Apache/2.2.') != -1

- name: Disable default conf
  sudo: yes
  shell: a2dissite 000-default.conf

- name: Enable conf
  sudo: yes
  shell: a2ensite {{ ws_vhost_env }}.conf
